#Example of pre-built Windows VM built in fusion and deployed to the Edge
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: winvm1
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-xsmall
  #http or https location of OVA without the prefix:
  imageName: "/vmfs/volumes/66b2ca85-8d638f12-201c-0050569e0757/tinywin.ova"
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
